name: CI

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]


jobs:
  build:
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      - uses: actions/checkout@v2
      - name: Compile Java Classes
        run: 
          cd Projects/P2
  
  TestGhostValidMoves:
      runs-on: ubuntu-latest
      container: openjdk:13
      steps:
        - uses: actions/checkout@v2
        - name: Run tests
          run: 
            cd Projects/P2
            gradlew test --parallel --tests TestGhostInRange

  TestMapMove:
      runs-on: ubuntu-latest
      container: openjdk:13
      steps:
        - uses: actions/checkout@v2
        - name: Run tests
          run: 
            cd Projects/P2
            gradlew test --parallel --tests TestMapAttack

  TestPacManValidMoves:
      runs-on: ubuntu-latest
      container: openjdk:13
      steps:
        - uses: actions/checkout@v2
        - name: Run tests
          run: 
            cd Projects/P2
            gradlew test --parallel --tests TestPacManInRange